# Generated by Django 4.2.24 on 2025-10-09 14:57

from django.db import migrations, models
import photo_metadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=photo_metadata.models.get_upload_path, verbose_name='Файл JSON')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Валидный файл')),
            ],
            options={
                'verbose_name': 'Импортированный файл',
                'verbose_name_plural': 'Импортированные файлы',
            },
        ),
        migrations.CreateModel(
            name='PhotoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('format', models.CharField(choices=[('JPEG', 'JPEG'), ('PNG', 'PNG'), ('GIF', 'GIF'), ('BMP', 'BMP'), ('TIFF', 'TIFF')], max_length=10, verbose_name='Формат')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (байт)')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина (px)')),
                ('height', models.PositiveIntegerField(verbose_name='Высота (px)')),
                ('camera_make', models.CharField(blank=True, max_length=100, verbose_name='Производитель камеры')),
                ('camera_model', models.CharField(blank=True, max_length=100, verbose_name='Модель камеры')),
                ('exposure_time', models.CharField(blank=True, max_length=20, verbose_name='Выдержка')),
                ('aperture', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Диафрагма')),
                ('iso', models.PositiveIntegerField(blank=True, null=True, verbose_name='ISO')),
                ('focal_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Фокусное расстояние')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('capture_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата съемки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Теги (через запятую)')),
            ],
            options={
                'verbose_name': 'Метаданные фотографии',
                'verbose_name_plural': 'Метаданные фотографий',
            },
        ),
    ]
